blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/yourusername/bodigi_loop_build/blob/main/docs/README.md
    about: Check our comprehensive documentation first
  - name: 💬 Discussions
    url: https://github.com/yourusername/bodigi_loop_build/discussions
    about: Ask questions and discuss ideas with the community
